const express = require('express');
const route = express.Router();
const verify = require('../controllers/verify');
const {addQuestion, getQuestionForTeacher, questionSetByTeacher, getQuestionForStudent, getResultQuestions} = require('../controllers/question');
route.post('/addQuestion', addQuestion);
// route.get('/teacher/question', verify, getQuestionForTeacher);
// route.post('/teacher/question', verify, questionSetByTeacher);
route.post('/student/question', getQuestionForStudent);
route.post('/student/result/question', getResultQuestions);
module.exports = route;