const express = require('express');
const route = express.Router();
const {register, login, saveResult, getResult, getChapterWisePerformance, getAssignedQuestionByTeacher, getDashboard, getTopCard} = require('../../controllers/user/student');
route.post('/student/register', register);
route.post('/student/login', login);
route.post('/student/saveresult', saveResult);
route.get('/student/getresults', getResult);
route.get('/student/performance/chapterwise', getChapterWisePerformance);
route.get('/student/teacher/question', getAssignedQuestionByTeacher);
route.get('/student/dashboard', getDashboard);
route.get('/student/gettopcard', getTopCard);
module.exports = route;